### ISSUE TITLE
sfera

### ISSUE THREAD

**Issue by FabioZTessitore** [LeonardoRiselli/python#3]
```py
s = 4*math.pi*(r*r)
v= 4/3*math.pi*(r*r*r)
```
1. le parentesi sono inutili
2. quando si fanno calcoli dovresti usare float

**Comment by LeonardoRiselli** [comment]
ok prof ho tolto le parentesi ma il float non è gia attico dato che il math.pi ha la virgola o devo mettere nei calcoli i numeri con la virgola esempio 4.0?

**Comment by FabioZTessitore** [comment]
la tua osservazione è giusta per s (però conviene comunque mettere 4.0, non puoi sapere come evolverà il codice, ed in ogni caso è più chiaro)
invece per v c'è proprio un errore (quanto fa 4/3 ?)

**Comment by LeonardoRiselli** [comment]
Ok prof ora carico il programma aggiustato

Il 14 dic 2016 14:51, "Fabio Z Tessitore" <notifications@github.com> ha
scritto:

**Comment by LeonardoRiselli** [comment]
fatto prof ho messo il float e al posto di 4/3 ho messo 1.33

**Comment by FabioZTessitore** [comment]
ancora non va bene. quando si programma bisogna essere chiari. Nessuno capisce la formula con 1.33

**Comment by LeonardoRiselli** [comment]
fatto prof ho messo a posto il programma rimettendo 4.0/3.0 al posto di 1.33
