### ISSUE TITLE
Volume

### ISSUE THREAD

**Issue by FabioZTessitore** [LeonardoRiselli/python#4]
Il programma va bene, puoi aggiustare solo le stampe in modo da avere l'output così come richiesto dall'esercizio?

**Comment by FabioZTessitore** [comment]
c'è ancora questo

**Comment by LeonardoRiselli** [comment]
Come lo devo impostare output?

**Comment by FabioZTessitore** [comment]
così come chiedeva l'esercizio, vai a controllare

**Comment by LeonardoRiselli** [comment]
Ok ora controllo e aggiusto

Il 22 dic 2016 15:02, "Fabio Z Tessitore" <notifications@github.com> ha
scritto:

**Comment by LeonardoRiselli** [comment]
l'ho ricaricato

**Comment by FabioZTessitore** [comment]
lo vedi che faccio bene ad insistere?
Si può avere un output come questo?

```
Calcolo del volume di un cubo o di una sfera
Effettua una scelta (1 - Cubo, 2 - Sfera)
? 1
Lato del cubo: 2
Il cubo di lato 2 ha volume 8
```

**Comment by LeonardoRiselli** [comment]
Subito

Il 22 dic 2016 16:00, "Fabio Z Tessitore" <notifications@github.com> ha
scritto:

**Comment by LeonardoRiselli** [comment]
caricato
