### ISSUE TITLE
Equazioni di Primo Grado

### ISSUE THREAD

**Issue by FabioZTessitore** [LeonardoRiselli/python#5]
Sai cos'è un'equazione di primo grado?

**Comment by LeonardoRiselli** [comment]
Mettere da un lato la x e fare le operazioni tra loro e dall altro lato i numeri senza la x per fare le operazioni tra loro

**Comment by FabioZTessitore** [comment]
Per fortuna non dobbiamo fare italiano ...

Data l'equazione `a x + b = 0` qual è la soluzione `x`?

**Comment by LeonardoRiselli** [comment]
La soluzione dovrebbe essere x=ab

Il 22 dic 2016 13:55, "Fabio Z Tessitore" <notifications@github.com> ha
scritto:

**Comment by FabioZTessitore** [comment]
Falso

**Comment by LeonardoRiselli** [comment]
Scusate prof avevo visto male la soluzione é ax=b che poi dividendo tutti e due per a diventa x=b/a

**Comment by FabioZTessitore** [comment]
Falso ancora

**Comment by LeonardoRiselli** [comment]
Scusate prof ax=-b che diventa x=-b/a

**Comment by FabioZTessitore** [comment]
ok, ci siamo
adesso inizia a scrivere un programma che chiede a e b e calcola x

**Comment by LeonardoRiselli** [comment]
In poche parole devo fare un programma che mi chiede il valore delle
variabili a e b che calcola il valore di x

Il 22 dic 2016 15:03, "Fabio Z Tessitore" <notifications@github.com> ha
scritto:

**Comment by LeonardoRiselli** [comment]
caricato

**Comment by FabioZTessitore** [comment]
```py
if a<0:
  x=a-b
else:
  x=a+b
```
questa cosa è la stessa che hai scritto prima secondo te?

**Comment by LeonardoRiselli** [comment]
In che senso

Il 22 dic 2016 16:01, "Fabio Z Tessitore" <notifications@github.com> ha
scritto:

**Comment by FabioZTessitore** [comment]
quando ti ho chiesto qual è la soluzione dell'equazione a x + b = 0 cosa hai risposto?

**Comment by LeonardoRiselli** [comment]
Che era uguale a x=-b/a

Il 22 dic 2016 16:05, "Fabio Z Tessitore" <notifications@github.com> ha
scritto:

**Comment by LeonardoRiselli** [comment]
Ok fo capito dove ho sbagliato

Il 22 dic 2016 16:06, ha scritto:

**Comment by LeonardoRiselli** [comment]
prof ma per stampare un risultato inmezzo ad una frase devo fare 
print"frase 1",variabile"frasec2"
??

**Comment by FabioZTessitore** [comment]
print "frase 1", variabile, "frase 2"

attenzione alle virgole

**Comment by LeonardoRiselli** [comment]
Ok grazie prof

Il 22 dic 2016 17:02, "Fabio Z Tessitore" <notifications@github.com> ha
scritto:

**Comment by LeonardoRiselli** [comment]
caricato prof

**Comment by FabioZTessitore** [comment]
mi spieghi per quale motivo controlli se b è negativo?

**Comment by LeonardoRiselli** [comment]
perche se lo è quando lo porto dall'altro lato lo fa diventare positivo

**Comment by FabioZTessitore** [comment]
e se non lo è?

**Comment by LeonardoRiselli** [comment]
va in else e lo fa diventare negativo

**Comment by FabioZTessitore** [comment]
ok. Ora ti rendi conto che le istruzioni presenti nel ramo if e quelle nel ramo else sono identiche?

**Comment by LeonardoRiselli** [comment]
Si prof perché se io moltiplico un numero positivo per uno negativo il
numero diventa negativo se io moltiplico un numero negati o per un altro
negativo il numero è positivo

Il 22 dic 2016 17:28, "Fabio Z Tessitore" <notifications@github.com> ha
scritto:

**Comment by FabioZTessitore** [comment]
le operazioni nel ramo if e quelle nel ramo else sono **identiche**
Non ha senso mettere quell'if

**Comment by LeonardoRiselli** [comment]
A ok ora ho capito

Il 22 dic 2016 18:23, "Fabio Z Tessitore" <notifications@github.com> ha
scritto:

**Comment by LeonardoRiselli** [comment]
fatto prof caricato

**Comment by FabioZTessitore** [comment]
non ci stiamo capendo.
provo a fare un paio di esempi:
```
a = 2
b = 6

x = 3


a = 2
b = -6

x = -3
```

il risultato x si calcola sempre con la stessa formula `x = -b/a`

**Comment by LeonardoRiselli** [comment]
forse ho capito come devo fare

**Comment by LeonardoRiselli** [comment]
La stp caricando

Il 22 dic 2016 18:51, "Fabio Z Tessitore" <notifications@github.com> ha
scritto:

**Comment by LeonardoRiselli** [comment]
Fatto

Il 22 dic 2016 18:59, "Leonardo jr Riselli" <juniorriselli@gmail.com> ha
scritto:

**Comment by FabioZTessitore** [comment]
mi sa che devi staccare. hai bisogno di una pausa. riprendiamo domani

**Comment by LeonardoRiselli** [comment]
Ok prof
Buona serata

Il 22 dic 2016 19:02, "Fabio Z Tessitore" <notifications@github.com> ha
scritto:

**Comment by FabioZTessitore** [comment]
aspetto aggiornamenti

**Comment by LeonardoRiselli** [comment]
prof scusate mi ero completamente dimenticato ho caricato quelle di primo grado e quelle di secondo

**Comment by LeonardoRiselli** [comment]
quelle d primo grado non so bene dove modificarlo

**Comment by FabioZTessitore** [comment]
riprendiamo il discorso.
fai come hai fatto per quelle di secondo grado. Cioè dopo l'input dei coefficienti a e b fai il calcolo della soluzione e stampi il risultato.
Poi pensiamo ai casi particolari

**Comment by LeonardoRiselli** [comment]
prof l'ho caricata ma non so se va bene

**Comment by FabioZTessitore** [comment]
devi togliere tutte le cose che ti sei inventato

1. le moltiplicazioni per -1
2. il controllo se a è multiplo di b

ps. per fare la negazione di un numero non serve fare la moltiplicazione per -1, basta far precedere la variabile dal segno - (es. `x = -b / a`)

**Comment by LeonardoRiselli** [comment]
ok correggo subito

**Comment by LeonardoRiselli** [comment]
caricato

**Comment by FabioZTessitore** [comment]
ti ho detto di togliere quell'if
poi controlla la formula per il calcolo della x

**Comment by LeonardoRiselli** [comment]
così prof?

**Comment by FabioZTessitore** [comment]
ok, ma la formula è sbagliata

**Comment by LeonardoRiselli** [comment]
fatto prof aggiustato

**Comment by FabioZTessitore** [comment]
ok, adesso abbiamo un punto di partenza.
Il programma funziona, tranne che in certi casi particolari.
Mi sai dire quali sono?

**Comment by LeonardoRiselli** [comment]
Si quando x=0 credo

Il 30 dic 2016 14:57, "Fabio Z Tessitore" <notifications@github.com> ha
scritto:

ok, adesso abbiamo un punto di partenza.
Il programma funziona, tranne che in certi casi particolari.
Mi sai dire quali sono?

—
You are receiving this because you were assigned.
Reply to this email directly, view it on GitHub
<https://github.com/LeonardoRiselli/python/issues/5#issuecomment-269774370>,
or mute the thread

**Comment by FabioZTessitore** [comment]
la x è un valore di output. I dati del problema sono a e b

**Comment by LeonardoRiselli** [comment]
Ok fino a qui ci sono

Il 30 dic 2016 15:52, "Fabio Z Tessitore" <notifications@github.com> ha
scritto:

**Comment by FabioZTessitore** [comment]
e mi devi dire quali sono i casi particolari in cui il programma non funziona

**Comment by LeonardoRiselli** [comment]
Uno di questi dovrebbe essere quando a è maggiore di b che si deve
semplificare poi altri non me li ricordo

Il 30 dic 2016 16:26, "Fabio Z Tessitore" <notifications@github.com> ha
scritto:

**Comment by FabioZTessitore** [comment]
immaginiamo a = 4 e b = 2
il tuo programma calcola x = -2/4 = 0.5
perché dici che non va bene?

**Comment by LeonardoRiselli** [comment]
No prof io pensavo che doveva uscire 1/2

Il 30 dic 2016 16:30, "Fabio Z Tessitore" <notifications@github.com> ha
scritto:

**Comment by FabioZTessitore** [comment]
ma assolutamente no, sarebbe un problema troppo complesso da fare ora

**Comment by FabioZTessitore** [comment]
piuttosto controlla che esca veramente 0.5 e correggi

**Comment by LeonardoRiselli** [comment]
A ok prof altri casi non me ne vengono in mente

Il 30 dic 2016 16:32, "Fabio Z Tessitore" <notifications@github.com> ha
scritto:

**Comment by FabioZTessitore** [comment]
pensaci un po' su.
nel frattempo cerca di far uscire 0.5 se metti a = 4 e b = 2

**Comment by FabioZTessitore** [comment]
vogliamo andare avanti?

**Comment by LeonardoRiselli** [comment]
Si scusate prof oggi non mi sono proprio applicato

Il 10 gen 2017 14:55, "Fabio Z Tessitore" <notifications@github.com> ha
scritto:

**Comment by LeonardoRiselli** [comment]
caricato prof ora si chiama primo_grado.py

**Comment by FabioZTessitore** [comment]
correggi il segno

**Comment by LeonardoRiselli** [comment]
subito prof


2017-01-13 14:56 GMT+01:00 Fabio Z Tessitore <notifications@github.com>:

**Comment by LeonardoRiselli** [comment]
caricato prof ora aggiusto quella di secondo grado e la mando

**Comment by FabioZTessitore** [comment]
non hai caricato

**Comment by LeonardoRiselli** [comment]
risolvo subito

**Comment by LeonardoRiselli** [comment]
caricato provate ora
