### ISSUE TITLE
secondo grado

### ISSUE THREAD

**Issue by FabioZTessitore** [LeonardoRiselli/python#6]
eq

**Comment by LeonardoRiselli** [comment]
caricata ma mi da un errore sulla riga 9

**Comment by FabioZTessitore** [comment]
3 cose:

1. l'errore è dovuto a lettera accentata
2. il calcolo del delta non ha senso dove l'hai messo.
3. controlla le soluzioni x1 e x2 (attento alle parentesi)

**Comment by LeonardoRiselli** [comment]
vedete se ora va bene prof

**Comment by FabioZTessitore** [comment]
restano da aggiustare le parentesi in x1 e x2
inoltre c'è il problema dei float come in quelle di primo grado

**Comment by LeonardoRiselli** [comment]
fatto

**Comment by FabioZTessitore** [comment]
Quelle parentesi non le vogliamo proprio aggiustare?

**Comment by LeonardoRiselli** [comment]
non riesco a capre quali parentesi

**Comment by FabioZTessitore** [comment]
Ti ricordi con quale ordine vengono eseguite le operazioni aritmetiche?
Correggi le formule?

Il 13 gen 2017 6:04 PM, "LeonardoRiselli" <notifications@github.com> ha
scritto:

**Comment by LeonardoRiselli** [comment]
prima tutte uguali a 0 poi solo a e b poi solo a

**Comment by FabioZTessitore** [comment]
Le formule di x1 e di x2. Dove stai guardando?

Il 13 gen 2017 6:10 PM, "LeonardoRiselli" <notifications@github.com> ha
scritto:

**Comment by LeonardoRiselli** [comment]
ok cioè devo fare -b+radicedelta/2.0*a -b-radicedelta /2.0*a giusto?

**Comment by FabioZTessitore** [comment]
Le parentesi. Non te lo dico più

Il 13 gen 2017 6:15 PM, "LeonardoRiselli" <notifications@github.com> ha
scritto:

**Comment by LeonardoRiselli** [comment]
ma quelle di -1.0?

**Comment by LeonardoRiselli** [comment]
caricato prof ho capito l'errore e che sono abbituato in matematica a mettere dopo una moltiplicazione se è un numero negatico per forza le parentesi

**Comment by FabioZTessitore** [comment]
Negativo

**Comment by LeonardoRiselli** [comment]
allora non riesco a capire quali

**Comment by LeonardoRiselli** [comment]
le uniche rimaste sul risultato x1 e x2 sono quelle di -1.0 non so se devo togliere queste.
